use std::cmp::Ordering;
use std::collections::{BTreeMap, HashMap};

use crate::diagnostics::{ChannelAllocation, EnvelopeEventCount, TrackSummary};
use crate::ir::{
    ChannelOverflowPolicy, ControlKind, ConversionOptions, ECommand, EnvelopeDefinition,
    EnvelopeMode, EnvelopeRef, IrEvent, LoopMarkerKind, Rational, SongIr, TempoEvent, TonePolicy,
    TrackKind,
};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RenderedEvent {
    pub track_index: usize,
    pub abs_tick: u64,
    priority: u8,
    pub kind: RenderedEventKind,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum RenderedEventKind {
    NoteOn {
        channel: u8,
        note: u8,
        velocity: u8,
    },
    NoteOff {
        channel: u8,
        note: u8,
        velocity: u8,
    },
    ControlChange {
        channel: u8,
        controller: u8,
        value: u8,
    },
    ProgramChange {
        channel: u8,
        program: u8,
    },
    Tempo {
        bpm: u32,
    },
    TimeSignature {
        numerator: u8,
        denominator_power: u8,
        clocks_per_metronome: u8,
        thirty_seconds_per_quarter: u8,
    },
    KeySignature {
        sharps_flats: i8,
        minor: bool,
    },
    MidiPort {
        port: u8,
    },
    Marker {
        source_track: Option<String>,
        text: String,
    },
    Text(String),
    TrackName(String),
    EndOfTrack,
}

pub fn render_smf(song: &mut SongIr, options: &ConversionOptions) -> Result<Vec<u8>, String> {
    let events = collect_midi_events(song, options)?;
    encode_smf(&events, song.tracks.len() + 1, song.ppq)
}

pub fn collect_midi_events(
    song: &mut SongIr,
    options: &ConversionOptions,
) -> Result<Vec<RenderedEvent>, String> {
    song.diagnostics.track_summaries.clear();
    song.diagnostics.channel_allocations.clear();
    song.diagnostics.envelope_event_counts.clear();

    let assignments = allocate_channels(song, options)?;
    let shared_channel_counts = channel_counts(&assignments);
    let mut events = Vec::new();

    events.push(RenderedEvent::meta(
        0,
        0,
        0,
        RenderedEventKind::TrackName(
            song.title
                .clone()
                .unwrap_or_else(|| "mgs2smf conductor".to_string()),
        ),
    ));
    if let Some(title) = &song.title {
        events.push(RenderedEvent::meta(
            0,
            0,
            1,
            RenderedEventKind::Text(title.clone()),
        ));
    }
    events.push(RenderedEvent::meta(
        0,
        0,
        2,
        RenderedEventKind::Text("Generated by mgs2smf".to_string()),
    ));
    if let Some(input_file) = &song.diagnostics.input_file {
        events.push(RenderedEvent::meta(
            0,
            0,
            3,
            RenderedEventKind::Text(format!("Source MUS: {input_file}")),
        ));
    }
    events.push(RenderedEvent::meta(
        0,
        0,
        4,
        RenderedEventKind::TimeSignature {
            numerator: 4,
            denominator_power: 2,
            clocks_per_metronome: 24,
            thirty_seconds_per_quarter: 8,
        },
    ));
    events.push(RenderedEvent::meta(
        0,
        0,
        5,
        RenderedEventKind::KeySignature {
            sharps_flats: 0,
            minor: false,
        },
    ));
    if options.tone_policy == TonePolicy::TextMeta {
        for definition in &song.diagnostics.ignored_tone_definitions {
            events.push(RenderedEvent::meta(
                0,
                0,
                8,
                RenderedEventKind::Text(format!(
                    "MGS ignored tone {} line {}: {}",
                    definition.command,
                    definition
                        .line
                        .map(|line| line.to_string())
                        .unwrap_or_else(|| "unknown".to_string()),
                    definition.text
                )),
            ));
        }
    }

    let tempo_map = normalize_tempo_events(song);
    let tempo_points = tempo_points(&tempo_map, song.ppq);
    for tempo in &tempo_map {
        events.push(RenderedEvent::meta(
            0,
            tempo.at_steps.to_midi_ticks(song.ppq),
            6,
            RenderedEventKind::Tempo { bpm: tempo.bpm },
        ));
    }

    for track in &song.tracks {
        for event in &track.events {
            if let IrEvent::LoopMarker { at_steps, kind } = event {
                let text = match kind {
                    LoopMarkerKind::Start => options.loop_marker_start.as_str(),
                    LoopMarkerKind::End => options.loop_marker_end.as_str(),
                };
                events.push(RenderedEvent::meta(
                    0,
                    at_steps.to_midi_ticks(song.ppq),
                    7,
                    RenderedEventKind::Marker {
                        source_track: Some(track.source_id.clone()),
                        text: text.to_string(),
                    },
                ));
            }
        }
    }

    for track_offset in 0..song.tracks.len() {
        let track = song.tracks[track_offset].clone();
        let midi_track = track_offset + 1;
        let assignment = assignments[track_offset];
        let channel = assignment.channel;
        let channel_is_shared = shared_channel_counts
            .get(&(assignment.port, assignment.channel))
            .copied()
            .unwrap_or(0)
            > 1;
        song.diagnostics
            .channel_allocations
            .push(ChannelAllocation {
                source_track: track.source_id.clone(),
                midi_track,
                midi_channel: channel,
                midi_port: assignment.port,
            });

        events.push(RenderedEvent::meta(
            midi_track,
            0,
            0,
            RenderedEventKind::MidiPort {
                port: assignment.port,
            },
        ));
        events.push(RenderedEvent::meta(
            midi_track,
            0,
            1,
            RenderedEventKind::TrackName(format!("MGS {}", track.source_id)),
        ));

        let mut note_count = 0usize;
        let mut cc_count = 0usize;
        let mut env_counts: HashMap<String, usize> = HashMap::new();
        let mut warned_shared_envelope_suppression = false;

        for ir_event in &track.events {
            match ir_event {
                IrEvent::Note {
                    start_steps,
                    duration_steps,
                    note,
                    velocity,
                    tone: _,
                    envelope,
                } => {
                    let start_tick = start_steps.to_midi_ticks(song.ppq);
                    let end_tick = start_steps.add(*duration_steps).to_midi_ticks(song.ppq);
                    let duration_ticks = end_tick.saturating_sub(start_tick).max(1);
                    let mut note_velocity = *velocity;

                    if let Some(reference) = envelope {
                        match options.envelope_mode {
                            EnvelopeMode::Cc11 | EnvelopeMode::Cc7 => {
                                if channel_is_shared {
                                    if !warned_shared_envelope_suppression {
                                        song.diagnostics.add_unsupported(
                                            None,
                                            Some(track.source_id.clone()),
                                            "envelope CC on shared MIDI channel",
                                            "suppressed to avoid channel mixing",
                                        );
                                        warned_shared_envelope_suppression = true;
                                    }
                                    events.push(RenderedEvent::channel(
                                        midi_track,
                                        start_tick,
                                        30,
                                        RenderedEventKind::NoteOn {
                                            channel,
                                            note: *note,
                                            velocity: note_velocity,
                                        },
                                    ));
                                    events.push(RenderedEvent::channel(
                                        midi_track,
                                        end_tick,
                                        20,
                                        RenderedEventKind::NoteOff {
                                            channel,
                                            note: *note,
                                            velocity: 0,
                                        },
                                    ));
                                    note_count += 1;
                                    continue;
                                }
                                let controller = match options.envelope_mode {
                                    EnvelopeMode::Cc11 => 11,
                                    EnvelopeMode::Cc7 => 7,
                                    _ => unreachable!(),
                                };
                                let cc_events = render_envelope_cc(
                                    song,
                                    *reference,
                                    start_tick,
                                    duration_ticks,
                                    &tempo_points,
                                    controller,
                                    &track.source_id,
                                );
                                cc_count += cc_events.len();
                                *env_counts.entry(envelope_name(*reference)).or_insert(0) +=
                                    cc_events.len();
                                for (offset, controller, value) in cc_events {
                                    events.push(RenderedEvent::channel(
                                        midi_track,
                                        start_tick + offset,
                                        10,
                                        RenderedEventKind::ControlChange {
                                            channel,
                                            controller,
                                            value,
                                        },
                                    ));
                                }
                            }
                            EnvelopeMode::NoteVelocity => {
                                if let Some(value) = first_envelope_value(
                                    song,
                                    *reference,
                                    start_tick,
                                    duration_ticks,
                                    &tempo_points,
                                ) {
                                    note_velocity = scale_velocity(note_velocity, value);
                                }
                            }
                            EnvelopeMode::SplitVelocity => {
                                let segments = render_split_velocity_segments(
                                    song,
                                    *reference,
                                    start_tick,
                                    duration_ticks,
                                    &tempo_points,
                                    note_velocity,
                                    &track.source_id,
                                );
                                if !segments.is_empty() {
                                    *env_counts.entry(envelope_name(*reference)).or_insert(0) +=
                                        segments.len();
                                    for (offset_start, offset_end, velocity) in segments {
                                        events.push(RenderedEvent::channel(
                                            midi_track,
                                            start_tick + offset_start,
                                            30,
                                            RenderedEventKind::NoteOn {
                                                channel,
                                                note: *note,
                                                velocity,
                                            },
                                        ));
                                        events.push(RenderedEvent::channel(
                                            midi_track,
                                            start_tick + offset_end,
                                            20,
                                            RenderedEventKind::NoteOff {
                                                channel,
                                                note: *note,
                                                velocity: 0,
                                            },
                                        ));
                                    }
                                    note_count += 1;
                                    continue;
                                }
                            }
                            EnvelopeMode::Off => {}
                        }
                    }

                    events.push(RenderedEvent::channel(
                        midi_track,
                        start_tick,
                        30,
                        RenderedEventKind::NoteOn {
                            channel,
                            note: *note,
                            velocity: note_velocity,
                        },
                    ));
                    events.push(RenderedEvent::channel(
                        midi_track,
                        end_tick,
                        20,
                        RenderedEventKind::NoteOff {
                            channel,
                            note: *note,
                            velocity: 0,
                        },
                    ));
                    note_count += 1;
                }
                IrEvent::Control { at_steps, kind } => match kind {
                    ControlKind::Tone(tone) => match options.tone_policy {
                        TonePolicy::Ignore => {}
                        TonePolicy::GmProgram => {
                            events.push(RenderedEvent::channel(
                                midi_track,
                                at_steps.to_midi_ticks(song.ppq),
                                15,
                                RenderedEventKind::ProgramChange {
                                    channel,
                                    program: gm_program(*tone),
                                },
                            ));
                        }
                        TonePolicy::TextMeta => {
                            events.push(RenderedEvent::meta(
                                midi_track,
                                at_steps.to_midi_ticks(song.ppq),
                                15,
                                RenderedEventKind::Text(format!("MGS tone @{tone}")),
                            ));
                        }
                    },
                    ControlKind::Envelope(_) => {}
                    ControlKind::Text(id) => {
                        let tick = at_steps.to_midi_ticks(song.ppq);
                        if let Some(text) = song.control_texts.get(id) {
                            events.push(RenderedEvent::meta(
                                midi_track,
                                tick,
                                15,
                                RenderedEventKind::Text(text.clone()),
                            ));
                        } else {
                            song.diagnostics.add_parse_warning(
                                None,
                                Some(track.source_id.clone()),
                                format!("undefined control text @m{id}"),
                            );
                        }
                    }
                },
                IrEvent::Rest { .. } | IrEvent::Tempo { .. } | IrEvent::LoopMarker { .. } => {}
            }
        }

        for (envelope, event_count) in env_counts {
            song.diagnostics
                .envelope_event_counts
                .push(EnvelopeEventCount {
                    track: track.source_id.clone(),
                    envelope,
                    event_count,
                });
        }

        song.diagnostics.track_summaries.push(TrackSummary {
            source_track: track.source_id.clone(),
            midi_track,
            midi_channel: channel,
            midi_port: assignment.port,
            source_steps: track.length_steps.to_source_step_json(),
            note_count,
            cc_count,
        });
    }

    add_end_of_track_events(&mut events, song.tracks.len() + 1);
    events.sort_by_key(|event| (event.track_index, event.abs_tick, event.priority));
    Ok(events)
}

impl RenderedEvent {
    fn channel(track_index: usize, abs_tick: u64, priority: u8, kind: RenderedEventKind) -> Self {
        Self {
            track_index,
            abs_tick,
            priority,
            kind,
        }
    }

    fn meta(track_index: usize, abs_tick: u64, priority: u8, kind: RenderedEventKind) -> Self {
        Self {
            track_index,
            abs_tick,
            priority,
            kind,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct ChannelAssignment {
    port: u8,
    channel: u8,
}

fn allocate_channels(
    song: &mut SongIr,
    options: &ConversionOptions,
) -> Result<Vec<ChannelAssignment>, String> {
    let reserve_rhythm_channel = song
        .tracks
        .iter()
        .any(|track| track.kind == TrackKind::Rhythm);
    let melodic_channels: Vec<u8> = (0..=15)
        .filter(|channel| !(reserve_rhythm_channel && *channel == 9))
        .collect();
    let melodic_count = song
        .tracks
        .iter()
        .filter(|track| track.kind == TrackKind::Melodic)
        .count();
    let overflow = melodic_count > melodic_channels.len();

    if overflow {
        match options.channel_overflow {
            ChannelOverflowPolicy::Error => {
                return Err(format!(
                    "MIDI channel overflow: {melodic_count} melodic source tracks require more than {} available channels",
                    melodic_channels.len()
                ));
            }
            ChannelOverflowPolicy::Shared => {
                song.diagnostics.add_unsupported(
                    None,
                    None,
                    "channel-overflow shared",
                    "melodic source tracks share MIDI channels; envelope CC is suppressed on shared channels",
                );
            }
            ChannelOverflowPolicy::MultiPort => {}
        }
    }

    let mut assignments = Vec::with_capacity(song.tracks.len());
    let mut melodic_index = 0usize;

    for track in &song.tracks {
        if track.kind == TrackKind::Rhythm {
            assignments.push(ChannelAssignment {
                port: 0,
                channel: 9,
            });
            continue;
        }
        let channel = melodic_channels[melodic_index % melodic_channels.len()];
        let port = if overflow && options.channel_overflow == ChannelOverflowPolicy::MultiPort {
            (melodic_index / melodic_channels.len()).min(255) as u8
        } else {
            0
        };
        assignments.push(ChannelAssignment { port, channel });
        melodic_index += 1;
    }

    Ok(assignments)
}

fn channel_counts(assignments: &[ChannelAssignment]) -> HashMap<(u8, u8), usize> {
    let mut counts = HashMap::new();
    for assignment in assignments {
        *counts
            .entry((assignment.port, assignment.channel))
            .or_insert(0) += 1;
    }
    counts
}

fn normalize_tempo_events(song: &mut SongIr) -> Vec<TempoEvent> {
    if song.tempo_events.is_empty() {
        song.tempo_events.push(TempoEvent {
            at_steps: Rational::ZERO,
            bpm: 120,
            source: "default".to_string(),
            line: None,
        });
    }
    song.tempo_events.sort_by_key(|event| {
        (
            event.at_steps.to_midi_ticks(song.ppq),
            event.line.unwrap_or(usize::MAX),
        )
    });

    let mut by_tick: BTreeMap<u64, TempoEvent> = BTreeMap::new();
    for event in song.tempo_events.clone() {
        let tick = event.at_steps.to_midi_ticks(song.ppq);
        if let Some(existing) = by_tick.get(&tick) {
            if existing.bpm != event.bpm {
                song.diagnostics.add_parse_warning(
                    event.line,
                    None,
                    format!(
                        "conflicting tempo at tick {tick}: {} vs {}; keeping {}",
                        existing.bpm, event.bpm, event.bpm
                    ),
                );
            }
        }
        by_tick.insert(tick, event);
    }
    let normalized: Vec<_> = by_tick.into_values().collect();
    song.tempo_events = normalized.clone();
    normalized
}

fn tempo_points(tempo_map: &[TempoEvent], ppq: u16) -> Vec<(u64, u32)> {
    let mut points: Vec<_> = tempo_map
        .iter()
        .map(|event| (event.at_steps.to_midi_ticks(ppq), event.bpm.max(1)))
        .collect();
    points.sort_by_key(|(tick, _)| *tick);
    if points.first().map(|(tick, _)| *tick).unwrap_or(1) != 0 {
        points.insert(0, (0, 120));
    }
    points
}

fn tempo_at_tick(tempo_points: &[(u64, u32)], tick: u64) -> u32 {
    let mut bpm = 120;
    for (tempo_tick, tempo_bpm) in tempo_points {
        if *tempo_tick <= tick {
            bpm = (*tempo_bpm).max(1);
        } else {
            break;
        }
    }
    bpm
}

fn next_tempo_index(tempo_points: &[(u64, u32)], tick: u64) -> usize {
    tempo_points
        .iter()
        .position(|(tempo_tick, _)| *tempo_tick > tick)
        .unwrap_or(tempo_points.len())
}

fn max_count_for_duration(
    start_tick: u64,
    duration_ticks: u64,
    ppq: u16,
    tempo_points: &[(u64, u32)],
) -> u32 {
    let end_tick = start_tick.saturating_add(duration_ticks);
    let mut current_tick = start_tick;
    let mut bpm = tempo_at_tick(tempo_points, start_tick);
    let mut next_idx = next_tempo_index(tempo_points, start_tick);
    let mut count_duration = TimeFraction::zero();

    while current_tick < end_tick {
        let next_tick = tempo_points
            .get(next_idx)
            .map(|(tick, _)| (*tick).min(end_tick))
            .unwrap_or(end_tick);
        if next_tick > current_tick {
            let segment_ticks = next_tick - current_tick;
            count_duration = count_duration.add(TimeFraction::new(
                segment_ticks as u128 * 3600,
                bpm as u128 * ppq as u128,
            ));
            current_tick = next_tick;
        }
        if let Some((tempo_tick, tempo_bpm)) = tempo_points.get(next_idx).copied() {
            if tempo_tick == current_tick {
                bpm = tempo_bpm.max(1);
                next_idx += 1;
                continue;
            }
        }
        if next_tick == end_tick {
            break;
        }
    }

    count_duration.ceil_u32().min(100_000) + 1
}

fn count_to_tick(start_tick: u64, count: u32, ppq: u16, tempo_points: &[(u64, u32)]) -> u64 {
    if count == 0 {
        return start_tick;
    }

    let mut remaining = TimeFraction::new(count as u128, 60);
    let mut current_tick = start_tick;
    let mut bpm = tempo_at_tick(tempo_points, start_tick);
    let mut next_idx = next_tempo_index(tempo_points, start_tick);

    loop {
        if let Some((next_tick, next_bpm)) = tempo_points.get(next_idx).copied() {
            if next_tick <= current_tick {
                bpm = next_bpm.max(1);
                next_idx += 1;
                continue;
            }

            let segment_ticks = next_tick - current_tick;
            let segment_duration =
                TimeFraction::new(segment_ticks as u128 * 60, bpm as u128 * ppq as u128);
            if remaining <= segment_duration {
                let ticks = seconds_to_ticks(remaining, bpm, ppq).min(segment_ticks);
                return current_tick.saturating_add(ticks);
            }

            remaining = remaining.sub(segment_duration);
            current_tick = next_tick;
            bpm = next_bpm.max(1);
            next_idx += 1;
        } else {
            return current_tick.saturating_add(seconds_to_ticks(remaining, bpm, ppq));
        }
    }
}

fn seconds_to_ticks(duration: TimeFraction, bpm: u32, ppq: u16) -> u64 {
    let num = duration.num * bpm.max(1) as u128 * ppq as u128;
    let den = duration.den * 60;
    ((num + den / 2) / den).min(u64::MAX as u128) as u64
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct TimeFraction {
    num: u128,
    den: u128,
}

impl TimeFraction {
    fn zero() -> Self {
        Self { num: 0, den: 1 }
    }

    fn new(num: u128, den: u128) -> Self {
        debug_assert!(den != 0);
        if num == 0 {
            return Self::zero();
        }
        let gcd = gcd_u128(num, den);
        Self {
            num: num / gcd,
            den: den / gcd,
        }
    }

    fn add(self, rhs: Self) -> Self {
        Self::new(self.num * rhs.den + rhs.num * self.den, self.den * rhs.den)
    }

    fn sub(self, rhs: Self) -> Self {
        debug_assert!(self >= rhs);
        Self::new(self.num * rhs.den - rhs.num * self.den, self.den * rhs.den)
    }

    fn ceil_u32(self) -> u32 {
        ((self.num + self.den - 1) / self.den).min(u32::MAX as u128) as u32
    }
}

impl PartialOrd for TimeFraction {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for TimeFraction {
    fn cmp(&self, other: &Self) -> Ordering {
        (self.num * other.den).cmp(&(other.num * self.den))
    }
}

fn gcd_u128(mut a: u128, mut b: u128) -> u128 {
    while b != 0 {
        let r = a % b;
        a = b;
        b = r;
    }
    a.max(1)
}

fn render_envelope_cc(
    song: &mut SongIr,
    reference: EnvelopeRef,
    start_tick: u64,
    duration_ticks: u64,
    tempo_points: &[(u64, u32)],
    controller: u8,
    track_id: &str,
) -> Vec<(u64, u8, u8)> {
    match song.envelopes.get(reference) {
        Some(definition) => envelope_values(
            song.ppq,
            definition,
            start_tick,
            duration_ticks,
            tempo_points,
        )
        .into_iter()
        .map(|(offset, value)| (offset, controller, value))
        .collect(),
        None => {
            song.diagnostics.add_parse_warning(
                None,
                Some(track_id.to_string()),
                format!("undefined envelope {}", envelope_name(reference)),
            );
            Vec::new()
        }
    }
}

fn first_envelope_value(
    song: &mut SongIr,
    reference: EnvelopeRef,
    start_tick: u64,
    duration_ticks: u64,
    tempo_points: &[(u64, u32)],
) -> Option<u8> {
    song.envelopes.get(reference).and_then(|definition| {
        envelope_values(
            song.ppq,
            definition,
            start_tick,
            duration_ticks,
            tempo_points,
        )
        .first()
        .copied()
        .map(|(_, value)| value)
    })
}

fn render_split_velocity_segments(
    song: &mut SongIr,
    reference: EnvelopeRef,
    start_tick: u64,
    duration_ticks: u64,
    tempo_points: &[(u64, u32)],
    base_velocity: u8,
    track_id: &str,
) -> Vec<(u64, u64, u8)> {
    match song.envelopes.get(reference) {
        Some(definition) => {
            let values = envelope_values(
                song.ppq,
                definition,
                start_tick,
                duration_ticks,
                tempo_points,
            );
            split_velocity_segments(values, duration_ticks, base_velocity)
        }
        None => {
            song.diagnostics.add_parse_warning(
                None,
                Some(track_id.to_string()),
                format!("undefined envelope {}", envelope_name(reference)),
            );
            Vec::new()
        }
    }
}

fn split_velocity_segments(
    values: Vec<(u64, u8)>,
    duration_ticks: u64,
    base_velocity: u8,
) -> Vec<(u64, u64, u8)> {
    if duration_ticks == 0 {
        return Vec::new();
    }

    let mut by_offset = BTreeMap::new();
    by_offset.insert(0, 127);
    for (offset, value) in values {
        if offset < duration_ticks {
            by_offset.insert(offset, value);
        }
    }

    let points: Vec<(u64, u8)> = by_offset.into_iter().collect();
    let mut segments: Vec<(u64, u64, u8)> = Vec::new();
    for (idx, (start, value)) in points.iter().copied().enumerate() {
        let end = points
            .get(idx + 1)
            .map(|(next, _)| *next)
            .unwrap_or(duration_ticks);
        if end <= start {
            continue;
        }
        let velocity = scale_velocity(base_velocity, value);
        if let Some(last) = segments.last_mut() {
            if last.1 == start && last.2 == velocity {
                last.1 = end;
                continue;
            }
        }
        segments.push((start, end, velocity));
    }
    segments
}

fn envelope_values(
    ppq: u16,
    definition: EnvelopeDefinition<'_>,
    start_tick: u64,
    duration_ticks: u64,
    tempo_points: &[(u64, u32)],
) -> Vec<(u64, u8)> {
    let max_count = max_count_for_duration(start_tick, duration_ticks, ppq, tempo_points);
    let count_values = match definition {
        EnvelopeDefinition::E(env) => expand_e_counts(&env.commands, max_count),
        EnvelopeDefinition::R(env) => expand_r_counts(env, max_count),
    };

    let mut out = Vec::new();
    let mut last = None;
    for (count, value) in count_values {
        let absolute_tick = count_to_tick(start_tick, count, ppq, tempo_points);
        let offset = absolute_tick.saturating_sub(start_tick);
        if offset >= duration_ticks {
            continue;
        }
        if last == Some((offset, value)) {
            continue;
        }
        out.push((offset, value));
        last = Some((offset, value));
    }
    out
}

fn expand_e_counts(commands: &[ECommand], max_count: u32) -> Vec<(u32, u8)> {
    let mut prefix = Vec::new();
    let mut loop_body = Vec::new();
    let mut suffix = Vec::new();
    let mut saw_loop = false;
    let mut in_loop = false;
    let mut after_loop = false;

    for command in commands {
        match command {
            ECommand::LoopStart => {
                saw_loop = true;
                in_loop = true;
            }
            ECommand::LoopEnd => {
                in_loop = false;
                after_loop = true;
            }
            other => {
                if in_loop {
                    loop_body.push(other.clone());
                } else if after_loop {
                    suffix.push(other.clone());
                } else {
                    prefix.push(other.clone());
                }
            }
        }
    }
    if in_loop {
        suffix.clear();
    }

    let mut out = Vec::new();
    let mut count = 0u32;
    let mut current_level = 15u8;
    execute_e_commands(&prefix, &mut count, &mut current_level, max_count, &mut out);
    if saw_loop && !loop_body.is_empty() {
        let mut guard = 0;
        while count <= max_count && guard < 10_000 {
            let before = count;
            execute_e_commands(
                &loop_body,
                &mut count,
                &mut current_level,
                max_count,
                &mut out,
            );
            if count == before {
                break;
            }
            guard += 1;
        }
    }
    execute_e_commands(&suffix, &mut count, &mut current_level, max_count, &mut out);

    if out.is_empty() {
        out.push((0, 127));
    }
    out
}

fn execute_e_commands(
    commands: &[ECommand],
    count: &mut u32,
    current_level: &mut u8,
    max_count: u32,
    out: &mut Vec<(u32, u8)>,
) {
    for command in commands {
        if *count > max_count {
            break;
        }
        match *command {
            ECommand::Level(level) => {
                out.push((*count, level_to_cc(level)));
                *current_level = level;
                *count = (*count).saturating_add(1);
            }
            ECommand::Hold { level, count: hold } => {
                out.push((*count, level_to_cc(level)));
                *current_level = level;
                *count = (*count).saturating_add(hold.max(1));
            }
            ECommand::Ramp {
                target,
                count: ramp_count,
            } => {
                let start = *current_level as i32;
                let target_i = target as i32;
                let steps = ramp_count.max(1);
                for i in 0..steps {
                    if *count + i > max_count {
                        break;
                    }
                    let value = start + ((target_i - start) * (i as i32 + 1)) / steps as i32;
                    out.push((*count + i, level_to_cc(value.clamp(0, 15) as u8)));
                }
                *current_level = target;
                *count = (*count).saturating_add(steps);
            }
            ECommand::ToneChange(_)
            | ECommand::Noise(_)
            | ECommand::ModeChange { .. }
            | ECommand::RegisterWrite { .. }
            | ECommand::FrequencyOffset(_)
            | ECommand::LoopStart
            | ECommand::LoopEnd => {}
        }
    }
}

fn expand_r_counts(env: &crate::ir::EnvelopeR, max_count: u32) -> Vec<(u32, u8)> {
    let mut out = Vec::new();
    let mut volume = env.al as i32;
    let sustain_level = env.sl as i32;
    let mut phase = 0;

    for count in 0..=max_count {
        out.push((count, volume_255_to_cc(volume as u8)));
        match phase {
            0 => {
                if env.ar == 0 || volume >= 255 {
                    phase = 1;
                } else {
                    volume = (volume + env.ar as i32).min(255);
                }
            }
            1 => {
                if env.dr == 0 || volume <= sustain_level {
                    phase = 2;
                    volume = volume.max(sustain_level);
                } else {
                    volume = (volume - env.dr as i32).max(sustain_level);
                }
            }
            _ => {
                if env.sr > 0 {
                    volume = (volume - env.sr as i32).max(0);
                }
            }
        }
    }
    out
}

fn level_to_cc(level: u8) -> u8 {
    (((level as u16 * 127) + 7) / 15).min(127) as u8
}

fn volume_255_to_cc(volume: u8) -> u8 {
    (((volume as u16 * 127) + 127) / 255).min(127) as u8
}

fn scale_velocity(velocity: u8, expression: u8) -> u8 {
    (((velocity as u16 * expression as u16) + 63) / 127).clamp(1, 127) as u8
}

fn envelope_name(reference: EnvelopeRef) -> String {
    match reference {
        EnvelopeRef::E(id) => format!("@e{id}"),
        EnvelopeRef::R(id) => format!("@r{id}"),
    }
}

fn gm_program(tone: u8) -> u8 {
    match tone {
        0 => 40,
        1 => 24,
        2 => 0,
        3 => 73,
        4 => 71,
        5 => 68,
        6 => 56,
        7 => 16,
        8 => 60,
        9 => 80,
        10 => 6,
        11 => 11,
        12 => 38,
        13 => 32,
        14 => 33,
        _ => 0,
    }
}

fn add_end_of_track_events(events: &mut Vec<RenderedEvent>, track_count: usize) {
    for track_index in 0..track_count {
        let end_tick = events
            .iter()
            .filter(|event| event.track_index == track_index)
            .map(|event| event.abs_tick)
            .max()
            .unwrap_or(0);
        events.push(RenderedEvent::meta(
            track_index,
            end_tick,
            255,
            RenderedEventKind::EndOfTrack,
        ));
    }
}

fn encode_smf(events: &[RenderedEvent], track_count: usize, ppq: u16) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    out.extend_from_slice(b"MThd");
    push_u32_be(&mut out, 6);
    push_u16_be(&mut out, 1);
    push_u16_be(&mut out, track_count as u16);
    push_u16_be(&mut out, ppq);

    for track_index in 0..track_count {
        let mut track_events: Vec<_> = events
            .iter()
            .filter(|event| event.track_index == track_index)
            .cloned()
            .collect();
        track_events.sort_by_key(|event| (event.abs_tick, event.priority));
        let mut track_data = Vec::new();
        let mut last_tick = 0u64;
        for event in track_events {
            if event.abs_tick < last_tick {
                return Err("event ordering bug while writing SMF".to_string());
            }
            push_vlq(&mut track_data, (event.abs_tick - last_tick) as u32);
            encode_event(&mut track_data, &event.kind);
            last_tick = event.abs_tick;
        }
        out.extend_from_slice(b"MTrk");
        push_u32_be(&mut out, track_data.len() as u32);
        out.extend(track_data);
    }

    Ok(out)
}

fn encode_event(out: &mut Vec<u8>, kind: &RenderedEventKind) {
    match kind {
        RenderedEventKind::NoteOn {
            channel,
            note,
            velocity,
        } => out.extend_from_slice(&[0x90 | (channel & 0x0f), *note, *velocity]),
        RenderedEventKind::NoteOff {
            channel,
            note,
            velocity,
        } => out.extend_from_slice(&[0x80 | (channel & 0x0f), *note, *velocity]),
        RenderedEventKind::ControlChange {
            channel,
            controller,
            value,
        } => out.extend_from_slice(&[0xb0 | (channel & 0x0f), *controller, *value]),
        RenderedEventKind::ProgramChange { channel, program } => {
            out.extend_from_slice(&[0xc0 | (channel & 0x0f), *program])
        }
        RenderedEventKind::Tempo { bpm } => {
            let mpq = 60_000_000u32 / (*bpm).max(1);
            out.extend_from_slice(&[0xff, 0x51, 0x03]);
            out.push(((mpq >> 16) & 0xff) as u8);
            out.push(((mpq >> 8) & 0xff) as u8);
            out.push((mpq & 0xff) as u8);
        }
        RenderedEventKind::TimeSignature {
            numerator,
            denominator_power,
            clocks_per_metronome,
            thirty_seconds_per_quarter,
        } => out.extend_from_slice(&[
            0xff,
            0x58,
            0x04,
            *numerator,
            *denominator_power,
            *clocks_per_metronome,
            *thirty_seconds_per_quarter,
        ]),
        RenderedEventKind::KeySignature {
            sharps_flats,
            minor,
        } => out.extend_from_slice(&[0xff, 0x59, 0x02, *sharps_flats as u8, u8::from(*minor)]),
        RenderedEventKind::MidiPort { port } => out.extend_from_slice(&[0xff, 0x21, 0x01, *port]),
        RenderedEventKind::Marker { text, .. } => push_meta_text(out, 0x06, text),
        RenderedEventKind::Text(text) => push_meta_text(out, 0x01, text),
        RenderedEventKind::TrackName(text) => push_meta_text(out, 0x03, text),
        RenderedEventKind::EndOfTrack => out.extend_from_slice(&[0xff, 0x2f, 0x00]),
    }
}

fn push_meta_text(out: &mut Vec<u8>, meta_type: u8, text: &str) {
    out.extend_from_slice(&[0xff, meta_type]);
    push_vlq(out, text.len() as u32);
    out.extend_from_slice(text.as_bytes());
}

fn push_vlq(out: &mut Vec<u8>, mut value: u32) {
    let mut buffer = [0u8; 5];
    let mut idx = 4;
    buffer[idx] = (value & 0x7f) as u8;
    while {
        value >>= 7;
        value > 0
    } {
        idx -= 1;
        buffer[idx] = ((value & 0x7f) as u8) | 0x80;
    }
    out.extend_from_slice(&buffer[idx..=4]);
}

fn push_u16_be(out: &mut Vec<u8>, value: u16) {
    out.extend_from_slice(&value.to_be_bytes());
}

fn push_u32_be(out: &mut Vec<u8>, value: u32) {
    out.extend_from_slice(&value.to_be_bytes());
}
